"""empty message

Revision ID: af043e0e752f
Revises: 7d8d9ac6def4
Create Date: 2019-07-23 00:21:59.975300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af043e0e752f'
down_revision = '7d8d9ac6def4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('last_name', table_name='member')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('last_name', 'member', ['last_name'], unique=True)
    # ### end Alembic commands ###
